### ISSUE TITLE
OpenFOAM files and preprocessing settings

### ISSUE THREAD

**Issue by martenlienen** [yellowshippo/penn-neurips2022#1]
Hey,
do you also have the OpenFOAM files and the YAML files available that you used to generate and preprocess the data? That would be of great help to understand your work in detail.

Best,
Marten

**Comment by yellowshippo** [comment]
Hi,

Thank you for the issue! Let me consider it. Once I get a conclusion, I will come back here.

Regards,
Masanobu

**Comment by yellowshippo** [comment]
Hi Marten,

I have uploaded OpenFOAM data. Please find the updated README.md for more details: https://github.com/yellowshippo/penn-neurips2022#raw-data-for-the-incompressible-flow-dataset

The corresponding YAML file for preprocessing can be found here: https://github.com/yellowshippo/penn-neurips2022/blob/main/data/fluid/data.yml

Thank you very much,
Masanobu

**Comment by martenlienen** [comment]
Thanks!

**Comment by martenlienen** [comment]
It looks like you adapted your case from the motor bike example, though there are also files that are not included with the motor bike example. Do you remember which adaptations you made and which parts of the case files are actually relevant for the dataset?

**Comment by yellowshippo** [comment]
We added `FOsurfaceDistance` and `FOwriteCellVolumes` in the `system` directory, which enabled us to compute the distance from the wall and cell volumes. These are used for machine learning inputs.

In the `constant/triSurface` directory, we have many .obj files, which are necessary to define the shape for analysis.
